version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testpir
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_pir_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/testpir
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    command: java -jar app.jar